"""Branded one-pager generator using python-docx."""
from pathlib import Path
from datetime import datetime
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

OUTPUT_DIR = Path("output")

BRAND_COLOR = RGBColor(0x25, 0x63, 0xEB)
DARK = RGBColor(0x0F, 0x17, 0x2A)


def build_one_pager(
    product_name: str,
    tagline: str,
    features: list[str],
    audience: str,
    body_copy: str,
) -> str:
    """Generate a branded one-page marketing .docx file.

    Returns the absolute path of the generated document.
    """
    doc = Document()

    # Title
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run(product_name)
    run.bold = True
    run.font.size = Pt(28)
    run.font.color.rgb = BRAND_COLOR

    # Tagline
    sub = doc.add_paragraph()
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub_run = sub.add_run(tagline)
    sub_run.italic = True
    sub_run.font.size = Pt(13)
    sub_run.font.color.rgb = DARK

    doc.add_paragraph()

    # Audience
    aud_p = doc.add_paragraph()
    aud_label = aud_p.add_run("Target audience: ")
    aud_label.bold = True
    aud_p.add_run(audience)

    # Overview
    doc.add_heading("Overview", level=2)
    doc.add_paragraph(body_copy)

    # Features
    doc.add_heading("Key features", level=2)
    for f in features:
        doc.add_paragraph(f, style="List Bullet")

    # Footer
    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer.add_run(
        f"Generated by Qogen, {datetime.now().strftime('%Y-%m-%d')}"
    )
    footer_run.font.size = Pt(9)
    footer_run.font.color.rgb = DARK

    OUTPUT_DIR.mkdir(exist_ok=True)
    
    safe_name = product_name.lower().replace(" ", "_")
    out_path = OUTPUT_DIR / f"{safe_name}_one_pager.docx"
    doc.save(out_path)
    return str(out_path.resolve())